harnessApiVersion: '1.0'
type: PIPELINE
pipelineStages:
- type: ENV_STATE
  name: Deploy DEV
  parallel: false
  skipCondition:
    type: DO_NOT_SKIP
  stageName: STAGE 1
  workflowName: Deploy-HTTP-Tests
  workflowVariables:
  - name: API_URL
    value: http://${context.api_service.URL}
  - entityType: ENVIRONMENT
    name: Environment
    value: Dev
  - entityType: SERVICE
    name: Service
    value: diego-java-springboot-service
  - entityType: INFRASTRUCTURE_DEFINITION
    name: InfraDefinition_KUBERNETES
    value: Diego-Koala-GKE
- type: ENV_STATE
  name: Deploy QA
  parallel: false
  skipCondition:
    type: DO_NOT_SKIP
  stageName: STAGE 2
  workflowName: QA-Workflow
- type: APPROVAL
  name: Approval 2
  parallel: false
  properties:
    userGroups:
    - Account Administrator
    workflowVariables: null
    stageName: STAGE 3
    timeoutMillis: 1800000
    approvalStateType: USER_GROUP
    sweepingOutputName: ''
  skipCondition:
    type: DO_NOT_SKIP
  stageName: STAGE 3
- type: ENV_STATE
  name: Canary-Verification
  parallel: false
  skipCondition:
    type: DO_NOT_SKIP
  stageName: STAGE 4
  workflowName: Canary-Verification
  workflowVariables:
  - entityType: INFRASTRUCTURE_DEFINITION
    name: InfraDefinition_Kubernetes
    value: Diego-GKE-PROD
  - entityType: ENVIRONMENT
    name: Environment
    value: PROD
