---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: maven:3-jdk-11
  commands:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn test -B

- name: docker  
  image: plugins/docker
  settings:
    username: diegokoala
    password: 
      from_secret: DockerHub
    repo: diegokoala/java-restful-web-services
    tags:
      - latest
      - '1.1.0'
    environment:
      - DOCKER_LAUNCH_DEBUG=true