---
kind: pipeline
name: default
platform:
  os: linux
  arch: amd64
steps:
- name: build
  image: maven:3-jdk-11
  commands:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
- name: unit tests
  image: maven:3-jdk-11
  commands:
  - mvn test -B
- name: docker  
  image: plugins/docker
  settings:
    username: diegokoala
    password: 
      from_secret: DockerHub
    repo: diegokoala/java-restful-web-services
    tags:
      - latest
      - '1.1.2'
    environment:
      - DOCKER_LAUNCH_DEBUG=true
- name: harness-deploy
  image: luisredda/test-plugin
  settings:  
    application: "Harness Demo Application"
    type: "PIPELINE"
    entityname: "CD Pipeline"
    service: "search"
    build: "v6"
    accountid:
      from_secret: harness_acctid
    apikey: 
      from_secret: harness_secret
    body: |
     variableInputs: [ 
      {
        name: "Service"
        variableValue: {
          type: NAME
          value: "order-service"
        }
      }
      ], 
      serviceInputs: [ {
        name: "order-service", 
        artifactValueInput: {
          valueType: BUILD_NUMBER
          buildNumber: {
            buildNumber: "latest"
      artifactSourceName: "harness_todolist-sample"
          }
        }}  ]