---
kind: pipeline
name: default
platform:
  os: linux
  arch: amd64
steps:
- name: build
  image: maven:3-jdk-11
  commands:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
- name: unit tests
  image: maven:3-jdk-11
  commands:
  - mvn test -B
- name: docker  
  image: plugins/docker
  settings:
    username: guinogueira7
    password: 
      from_secret: DockerHub
    repo: guinogueira7/java-restful-web-services
    tags:
      - latest
      - '1.1.3'
    environment:
      - DOCKER_LAUNCH_DEBUG=true
    auto_tag: true
- name: harness-deploy
  image: guinogueira7/drone-harness-plugin
  settings:  
    application: "Harness Demo Application"
    type: "PIPELINE"
    entityname: "CD Pipeline"
    service: "search"
    build: "v6"
    accountid:
      from_secret: harness_acctid
    apikey: 
      from_secret: harness_secret
    service_name: "order-service"
    build_number: "latest"
    artifact_source_name: "harness_todolist-sample"
