---
apiVersion: v1
kind: Service
metadata:
  name: java-restful-web-services
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    app: java-restful-web-services
  type: LoadBalancer