apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name}}
  labels:
    app: {{.Values.name}}
    app.kubernetes.io/name: {{.Values.name}}
    app.kubernetes.io/component: {{.Values.component}}
spec:
  replicas: {{int .Values.replicas}}
  selector:
    matchLabels:
      app: {{.Values.name}}
      app.kubernetes.io/name: {{.Values.name}}
      app.kubernetes.io/component: {{.Values.component}}
  template:
    metadata:
      labels:
        app: {{.Values.name}}
        app.kubernetes.io/name: {{.Values.name}}
        app.kubernetes.io/component: {{.Values.component}}
    spec:
      containers:
      - name: {{.Values.name}}
        image: {{.Values.image}}
        args:
          - --bind_ip
          - 0.0.0.0
        resources:
          requests:
            cpu: {{.Values.cpu}}
            memory: {{.Values.memory}}
        ports:
        - containerPort: {{.Values.servicePort}}