harnessApiVersion: '1.0'
type: SETUP
commandUnitType: COMMAND
commandUnits:
- artifactVariableName: artifact
  commandUnitType: SCP
  deploymentType: SSH
  destinationDirectoryPath: $WINGS_RUNTIME_PATH
  name: Copy
  source: ARTIFACTS
- command: |-
    apt install -y mongodb
    systemctl status mongodb
    systemctl start mongodb
    systemctl enable mongodb
  commandUnitType: EXEC
  deploymentType: SSH
  name: MongoDB install
  scriptType: BASH
- command: |-
    sudo apt install npm

    npm install express
    npm install serve-favicon
    npm install morgan
    npm install fs
    npm install body-parser
    npm install method-override
    npm install errorhandler
  commandUnitType: EXEC
  deploymentType: SSH
  name: Intall App dependencies
  scriptType: BASH
- command: |-
    cd nodeJS_Employees_App
    cd EmployeeKoalaDB
    node app.js
  commandUnitType: EXEC
  deploymentType: SSH
  name: App Start
  scriptType: BASH
targetToAllEnv: true
