harnessApiVersion: '1.0'
type: SETUP
commandUnitType: COMMAND
commandUnits:
- command: |-
    apt-get install git-all
    git clone https://github.com/diegopereiraeng/nodeJS_Employees_App.git
    cd nodeJS_Employees_App
    tar -cvf harness-employee.tar EmployeeKoalaDB
  commandUnitType: EXEC
  deploymentType: SSH
  name: Exec
  scriptType: BASH
- command: |
    apt install -y mongodb
    systemctl status mongodb
    systemctl start mongodb
  commandUnitType: EXEC
  deploymentType: SSH
  name: MongoDB install
  scriptType: BASH
targetToAllEnv: true
