harnessApiVersion: '1.0'
type: SETUP
commandUnitType: COMMAND
commandUnits:
- artifactVariableName: artifact
  commandUnitType: SCP
  deploymentType: SSH
  destinationDirectoryPath: $WINGS_RUNTIME_PATH
  name: Copy Artifacts
  source: ARTIFACTS
- command: |-
    cd nodeJS_Employees_App
    cd EmployeeKoalaDB
    node app.js
  commandUnitType: EXEC
  deploymentType: SSH
  name: App Start
  scriptType: BASH
targetToAllEnv: true
