harnessApiVersion: '1.0'
type: SETUP
commandUnitType: COMMAND
commandUnits:
- artifactVariableName: artifact
  commandUnitType: SCP
  deploymentType: SSH
  destinationDirectoryPath: $WINGS_RUNTIME_PATH
  name: Copy Artifacts
  source: ARTIFACTS
- command: |-
    sudo apt-get -y install zip

    unzip -o ${artifact.metadata.URL}
  commandUnitType: EXEC
  deploymentType: SSH
  name: Expand Artifact
  scriptType: BASH
  workingDirectory: $WINGS_RUNTIME_PATH
- command: |-
    cd EmployeeKoalaDB
    node app.js
  commandUnitType: EXEC
  deploymentType: SSH
  name: App Start
  scriptType: BASH
  workingDirectory: $WINGS_RUNTIME_PATH
targetToAllEnv: true
