apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name}}-deployment
spec:
  replicas: {{int .Values.replicas}}
  selector:
    matchLabels:
      app: {{.Values.name}}
      role: master
      tier: backend
  template:
    metadata:
      labels:
        app: {{.Values.name}}
        role: master
        tier: backend
    spec:
      {{- if .Values.dockercfg}}
      imagePullSecrets:
      - name: {{.Values.name}}-dockercfg
      {{- end}}
      containers:
      - name: {{.Values.name}}
        image: {{.Values.image}}
        resources:
          requests:
            cpu: {{.Values.cpu}}
            memory: {{.Values.memory}}
        ports:
        - containerPort: {{.Values.servicePort}}