apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}
  labels:
    app: redis
    tier: backend
    role: master
spec:
  type: {{.Values.serviceType}}
  ports:
  - port: {{.Values.servicePort}}
    targetPort: {{.Values.serviceTargetPort}}
    protocol: TCP
  selector:
    app: {{.Values.name}}
    tier: {{.Values.tier}}
    role: {{.Values.role}}